type Position {
  id: ID!
  amount: BigInt!
  assetId: String!
  totalBaseRewardsEarned: BigInt!
}

type Builder {
  id: ID!
  owner: String!
  rewardAsset: String!
  # fundTime: Int!
  # endTime: Int!
  # rewards: BigInt!
}

type NewPositionEvent {
  id: ID!
  position: Position!
  txId: String!
}

type PositionBondingEvent {
  id: ID!
  position: Position!
  builder: Builder
  txId: String!
}

type RewardsClaimedEvent {
  id: ID!
  position: Position!
  txId: String!
  amount: BigInt!
}

type PositionDepositEvent {
  id: ID!
  position: Position!
  txId: String!
  amount: BigInt!
}

type BuilderBonding_BuilderRewardsExtendedEvent {
  id: ID!
}

type PositionWithdrawEvent {
  id: ID!
  position: Position!
  txId: String!
  amount: BigInt!
}

type BuilderBonding_BaseRewardsSyncedEvent {
  id: ID!
}

type BuilderBonding_ParametersSetEvent {
  id: ID!
}

type BuilderBonding_NewBuilderEvent {
  id: ID!
}

type BuilderBonding_BuilderOwnershipTransferredEvent {
  id: ID!
}

type BuilderBonding_OwnershipTransferredEvent {
  id: ID!
}

type BuilderBonding_BuilderRewardsFundedEvent {
  id: ID!
}
